######################################################################
# Automatically generated by qmake (2.01a) ?? 6? 28 11:27:49 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += messagebox.h
SOURCES += main.cpp messagebox.cpp
