######################################################################
# Automatically generated by qmake (2.01a)
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mydialog.h
SOURCES += main.cpp mydialog.cpp
