######################################################################
# Automatically generated by qmake (2.01a) ?? 12? 27 11:38:03 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += builtindialog.h
SOURCES += builtindialog.cpp main.cpp
