######################################################################
# Automatically generated by qmake (2.01a) ?? 12? 19 16:01:17 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += button.h calculator.h
SOURCES += button.cpp calculator.cpp main.cpp
